{% set name = "venn-abers" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/venn-abers-{{ version }}.tar.gz
  sha256: 326c99ee430e2f0e3270a3465b77c4052d42f0274cb0f932bf31bc87edd921d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scikit-learn
    - pandas

test:
  imports:
    - venn_abers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ip200/venn-abers
  summary: Venn-ABERS calibration package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
